### ISSUE TITLE
Add a splash screen

### ISSUE THREAD

**Issue by RohanKhatua** [ACM-VIT/CryptoDash#1]

**Comment by blyncnov** [comment]
I would like to work on this if you assign me to it

**Comment by RohanKhatua** [comment]
> I would like to work on this if you assign me to it

Sure, I'll assign it to you. 
You can find the app logo in the assets folder.
Make sure to send a screenshot and screen recording of the splash screen when done.

**Comment by blyncnov** [comment]
Okay good

**Comment by blyncnov** [comment]
I will like to show you, the code I got from GitHub, I notice there are some errors on it, so literally the screenshot below is showing the main.dart, that's what my refactor looks like 

![image](https://user-images.githubusercontent.com/66668114/194715371-6e92010d-1187-4075-9ffc-13f87f3ad6ca.png)

Preview


![Simulator Screen Shot - iPhone 14 Pro Max - 2022-10-08 at 16 35 33](https://user-images.githubusercontent.com/66668114/194715496-5ba70e09-08e2-4c1b-8b3c-31a181d26af3.png)

**Comment by blyncnov** [comment]
So then , i will start working on the splash screen

**Comment by RohanKhatua** [comment]
> So then , i will start working on the splash screen

Please make changes as necessary and then raise a pull request.

**Comment by blyncnov** [comment]
let me raise a request now regarding my changes, after you review that, then I will continue with the splash screen

**Comment by blyncnov** [comment]
I created a PR, please check

**Comment by RohanKhatua** [comment]
@blyncnov please create a PR for this issue with the correct branch
