### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by RohanKhatua** [ACM-VIT/CryptoDash#4]
In lib/currency_box.dart :-

1. Change each box to have only an outline instead of a solid background
2. Move the text field to the upper half of the box 
3. The lower half should contain a placeholder image of a graph (eg. https://media.istockphoto.com/photos/red-arrow-moving-up-over-graph-paper-background-picture-id1157569047?b=1&k=20&m=1157569047&s=170667a&w=0&h=WuWDeAI3g1y3Fvd5OdMukKhDZ8U03PnQ1DH0e6Gge1k=)

**Comment by 20RitikSingh** [comment]
I would like to work on this.

**Comment by RohanKhatua** [comment]
> I would like to work on this.

Sure, I'll assign it to you.
Make sure to send a screenshot and screen recording of the home screen when done.

**Comment by RohanKhatua** [comment]
@20RitikSingh I've noticed its been a while since you were assigned to this issue and no PR has been as of yet, could you please update me on your progress. Thanks.
