### ISSUE TITLE
Add launcher icon

### ISSUE THREAD

**Issue by RohanKhatua** [ACM-VIT/CryptoDash#5]
Add the launcher icon (the icon that is visible in the app menu)
You can find the logo in the assets folder

**Comment by davidjs11** [comment]
Could you please tell more information about where do you want to add the icon?

**Comment by RohanKhatua** [comment]
It is the app icon, the one which is clicked to open the app, you can check this out -  
https://www.dre.vanderbilt.edu/~schmidt/android/android-4.0/out/target/common/docs/doc-comment-check/guide/practices/ui_guidelines/icon_design_launcher.html

**Comment by sanjaysargam** [comment]
Plz assign me

**Comment by RohanKhatua** [comment]
Sure, I'll assign you.
Please upload a screenshot of the launcher icon when done.

**Comment by RohanKhatua** [comment]
@SanjaySargam I've noticed its been a while since you were assigned to this issue and no PR has been as of yet, could you please update me on your progress. Thanks.
