### ISSUE TITLE
Nav Bar

### ISSUE THREAD

**Issue by dubey2709** [ACM-VIT/CryptoDash#9]
Nav Bar to switch between current crypto stats, crypto related articles and User Profile

**Comment by RohanKhatua** [comment]
Sure I'll assign it to you. Make sure to make a new file for each screen under lib/screens. 
Upload a screenshot and screen recording when you're done.
The PR should be targeted at nav-bar branch, not master.

**Comment by dubey2709** [comment]
![image](https://user-images.githubusercontent.com/96309032/194756014-b8494c8c-ff36-4d8b-b8e5-1ac660bf5ac5.png)
![image](https://user-images.githubusercontent.com/96309032/194756040-d0b93631-5778-4972-83b4-75a3ddb432e8.png)
![image](https://user-images.githubusercontent.com/96309032/194756064-4e6d30c2-6290-49d8-99ba-6e850f404111.png)
![image](https://user-images.githubusercontent.com/96309032/194756165-6b636414-9704-4cf5-89aa-e5af67e38ffe.png)

**Comment by dubey2709** [comment]
Here is your Screenshots
can I make a pr now

**Comment by RohanKhatua** [comment]
Nav Bar added, PR merged.
